version: '3.3'

services:
  app:
    depends_on:
      - app_db
    image: "renatonascalves/bp-graphql-app:wp${WP_VERSION:-5.2.2}-php${PHP_VERSION:-7.2}"
    volumes:
      - '.:/var/www/html/wp-content/plugins/wp-graphql-buddypress'
      - './.log/app:/var/log/apache2'
    env_file: .env.dist
    environment:
      WP_URL: 'http://localhost:8091'
      WP_DOMAIN: 'localhost:8091'
      DB_HOST: app_db
      INCLUDE_WPGRAPHIQL: 1
    ports:
      - '8091:80'
    networks:
      local:

  app_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      wordpress
      MYSQL_USER:          wordpress
      MYSQL_PASSWORD:      wordpress
    ports:
      - '3306'
    networks:
      testing:
      local:

  testing:
    depends_on:
      - app_db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DESIRED_PHP_VERSION: "${PHP_VERSION:-7.3}"
        DESIRED_WP_VERSION: "${WP_VERSION:-5.2}"
    image: woographql-testing
    volumes:
      - '.:/var/www/html/wp-content/plugins/wp-graphql-buddypress'
      - './.log/testing:/var/log/apache2'
    env_file: .env.dist
    environment:
      WPGRAPHQL_BUDDYPRESS_AUTOLOAD: 1
      DB_HOST: app_db
      WP_URL: 'http://localhost'
      WP_DOMAIN: 'localhost'
    networks:
      testing:

networks:
  local:
  testing: