name: Feature or Enhancement Request
description: Request a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting your issue, please ensure that you read through existing issues so as to avoid creating duplicates. 🙏

  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the feature or enhancement you would like to see incorporated.
      placeholder: |
        I would like to see <...> incorporated into <...> so that <...> can be achieved.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Case
      description: Provide a detailed description of the use case for this feature/enhancement.
      placeholder: |
        When a user <...> they should be able to <...> so that they don't have to <...>.
    validations:
      required: true
