name: For Discussion
description: Open a topic for discussion
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting your issue, please ensure that you read through existing issues so as to avoid creating duplicates. 🙏

  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of topic you wish to open for discussion.
      placeholder: |
        Should this codebase consider <...> so that <...> can be achieved?
    validations:
      required: true
