name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-quality:
    uses: alleyinteractive/.github/.github/workflows/php-code-quality.yml@main
    with:
      php: 8.3

