name: Coding Standards

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coding-standards:
    uses: alleyinteractive/.github/.github/workflows/php-coding-standards.yml@main
    with:
      php: 8.3
