name: Deploy to WordPress.org

on:
  release:
    types: [ published ]

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl
          tools: composer:v2
          coverage: none

      - name: Install PHP dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: wp-graphql-buddypress

      - name: Create artifact
        run: |
          mkdir plugin-build
          composer archive -vvv --format=zip --file="plugin-build/wp-graphql-buddypress"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wp-graphql-buddypress
          path: plugin-build/wp-graphql-buddypress.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: plugin-build/wp-graphql-buddypress.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
