name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: "WP: ${{ matrix.wp_version }} - PHP: ${{ matrix.php }}"
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2, 8.3]
        multisite: [true, false]
        wp_version: ['6.1', 'latest']
        object: ["memcached", "redis"]
    uses: alleyinteractive/.github/.github/workflows/php-tests.yml@feature/php-tests-core-suite
    with:
      multisite: ${{ matrix.multisite }}
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wp_version }}
      object-cache: ${{ matrix.object }}
      test-suite: 'core-test-suite'
      package-directory: 'plugins/wp-graphql-buddypress'
