name: Unit Tests

on: pull_request

jobs:
  tests:
    name: "WP: ${{ matrix.wp_version }} - PHP: ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # do not fail fast, let all tests fail.
      matrix:
        php: ['8.0']
        wp_version: ['master']
        include:
          - php: '7.4'
            wp_version: '5.9'
          - php: '7.1'
            wp_version: '4.9'
    env:
      WP_ENV_PHP_VERSION: ${{ matrix.php }}
      WP_VERSION: ${{ matrix.wp_version }}

    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Log information
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_EVENT_NAME"
          npm --version
          node --version
          git --version
          php --version
          composer --version

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--ignore-platform-reqs"

      - name: Adjust wp-phpunit version
        run: |
          if [ ${{ env.WP_VERSION }} == '4.9' ]; then
            composer require --dev --update-with-all-dependencies phpunit/phpunit ^6;
            composer require --dev "wp-phpunit/wp-phpunit:4.9";
          fi

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install node modules
        run: npm ci --cache ~/.npm

      - name: Setup WordPress
        run: |
          echo "{\"core\":\"WordPress/WordPress#${WP_VERSION}\"}" >> .wp-env.override.json
          chmod -R 767 ./
          npm run wp-env start -- --update

      - name: Unit tests - single site
        run: npm run phpunit
        if: ${{ success() || failure() }}

      - name: Unit tests - MU Network
        run: npm run phpunit:mu
        if: ${{ success() || failure() }}

      - name: Stop Docker environment
        run: npm run wp-env stop
        if: ${{ success() || failure() }}
