name: Unit Tests

on: pull_request

jobs:
  tests:
    name: "WP: ${{ matrix.wp_version }} - PHP: ${{ matrix.php }} - (MU: ${{ matrix.multisite }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # do not fail fast, let all the failing tests fail.
      matrix:
        php: [8.0, 8.1]
        multisite: [0, 1]
        wp_version: ["latest"]
    env:
      WP_CORE_DIR: /tmp/wordpress/
      WP_VERSION: ${{ matrix.wp_version }}
      WP_MULTISITE: ${{ matrix.multisite }}
    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          tools: composer:v2
          coverage: none

      - name: Set up WordPress
        run: |
          bash <(curl -s "https://raw.githubusercontent.com/wp-cli/scaffold-command/main/templates/install-wp-tests.sh") wordpress_unit_tests root root localhost ${{ matrix.wp_version }}
          rm -rf "${WP_CORE_DIR}wp-content/plugins"
          mkdir -p "${WP_CORE_DIR}wp-content/plugins/wp-graphql-buddypress"
          rsync -a --exclude=.git . "${WP_CORE_DIR}wp-content/plugins/wp-graphql-buddypress"
          cd ${WP_CORE_DIR}wp-content/plugins/wp-graphql-buddypress && composer install

      - name: Run all tests
        run: |
          cd ${WP_CORE_DIR}wp-content/plugins/wp-graphql-buddypress
          composer phpunit
